apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-credentials
data:
  DB_HOST: {{ .Release.Name }}-mysql
  DB_NAME: {{ .Values.db.database }}
  DB_PASSWORD: {{ .Values.db.password }}
  DB_PORT: "3306"
  DB_USER: {{ .Values.db.username }}
