apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-root-password
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-init-script
          mountPath: /docker-entrypoint-initdb.d
        - name: mariadb-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-init-script
        configMap:
          name: {{ .Release.Name }}-mariadb-init-script
      - name: mariadb-pvc
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mariadb-pvc
