apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: {{ .Values.db.service.port }}
    targetPort: 3306
  type: {{ .Values.db.service.type }}
