apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-website
spec:
  ports:
  - port: {{ .Values.website.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: website
  type: {{ .Values.website.service.type }}
