apiVersion: v1
data:
  DB_HOST: "bXlzcWwtc2VydmljZQo="
  DB_NAME: "ZWNvbWRiCg=="
  DB_PASSWORD: "ZWNvbXBhc3N3b3JkCg=="
  DB_PORT: "MzMwNgo="
  DB_USER: "ZWNvbXVzZXIK"
kind: Secret
metadata:
  name: db-credentials