apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ecom-app
  name: website-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ecom-app
  type: LoadBalancer
status:
  loadBalancer: {}